export const LOADING_MOVIES = 'LOADING_MOVIES';
export const SORT_MOVIES_BY_RELEASE_DATE = 'SORT_MOVIES_BY_RELEASE_DATE';
export const SORT_MOVIES_BY_RATING = 'SORT_MOVIES_BY_RATING';
export const TOGGLE_SEARCH_OPRION = 'TOGGLE_SEARCH_OPRION';
export const SEARCH_MOVIES = 'SEARCH_MOVIES';
export const GET_MOVIE_BY_ID = 'GET_MOVIE_BY_ID';
export const CHANGE_SEACH_INPUT = 'CHANGE_SEACH_INPUT';
