export const LOAD_MOVIES = 'LOAD_MOVIES';
export const TOGGLE_SORT_OPRION = 'TOGGLE_SORT_OPRION';
export const TOGGLE_SEARCH_OPRION = 'TOGGLE_SEARCH_OPRION';
export const CLICK_ON_SEARCH = 'CLICK_ON_SEARCH';
export const GET_MOVIE_BY_ID = 'GET_MOVIE_BY_ID';
